app.name: product
product.count.max: 100

app:
  logging:
    request: true
    response: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    password: pass
    username: sa
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/testdb

  h2:
    console:
      path: /h2
      enabled: true

